### Test

GET http://localhost:3001/api/ping HTTP/1.1

### All (Exercises + cards + blocks)

DELETE http://localhost:3001/api/all HTTP/1.1

### Empty DB (Drops tables, also users)

DELETE http://localhost:3001/api/tables HTTP/1.1








### Exercises

GET http://localhost:3001/api/exercises HTTP/1.1

###

GET http://localhost:3001/api/exercise/1 HTTP/1.1

###

GET http://localhost:3001/api/exercise/1000 HTTP/1.1

###

POST http://localhost:3001/api/exercise HTTP/1.1
content-type: application/json

{
    "name": "Car parking slots"
}

###

PUT http://localhost:3001/api/exercise/1 HTTP/1.1
content-type: application/json

{
    "name": "Edited name",
    "turns": 24
}

###

DELETE http://localhost:3001/api/exercise/1 HTTP/1.1









### Cards

GET http://localhost:3001/api/cards HTTP/1.1

###

GET http://localhost:3001/api/cards/1 HTTP/1.1

###

GET http://localhost:3001/api/card/1 HTTP/1.1

###

POST http://localhost:3001/api/card HTTP/1.1
content-type: application/json

{
    "ex_id": 1,
    "name": "Employer starts the task of the day",
    "type": "bpmn",
    "cost": 4,
    "bonus": 0,
    "draws": 0,
    "buys": 0,
    "turns": 0,
    "bpmn": ""
}

###

PUT http://localhost:3001/api/card/1 HTTP/1.1
content-type: application/json

{
    "ex_id": 1,
    "name": "Card modificata",
    "type": "action",
    "cost": 2,
    "bonus": 0,
    "draws": 0,
    "buys": 0,
    "turns": 0,
    "bpmn": ""
}

###

DELETE http://localhost:3001/api/card/1 HTTP/1.1

###

DELETE http://localhost:3001/api/cards/1 HTTP/1.1

###

DELETE http://localhost:3001/api/cards/all/1 HTTP/1.1